

services:



  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - ./minio_data:/data

#  nginx:
#    image: nginx:latest
#    container_name: booking-nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"  # –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ, —á—Ç–æ–±—ã HTTPS —Ä–∞–±–æ—Ç–∞–ª
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - /etc/ssl/certificate:/etc/ssl/certificate:ro  # üîπ –ø—Ä–∏–º–æ–Ω—Ç–∏—Ä–æ–≤–∞—Ç—å —Å–∏—Å—Ç–µ–º–Ω—É—é –ø–∞–ø–∫—É –≤–Ω—É—Ç—Ä—å –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞
#    networks:
#      - photo_network



networks:
  photo_network:
    driver: bridge

volumes:
  minio_data: