services:
  app:
    container_name: photo_app
    build: .
    ports:
      - "5000:5000"
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: likes
      S3_REGION: us-east-1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      DB_PATH: /data/likes.db
    volumes:
      - ./data:/data
      - ./gallery.html:/app/gallery.html:ro
    depends_on:
      - minio
    networks:
      - photo_network

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: ["server", "--console-address", ":9001", "/data"]
    volumes:
      - ./minio_data:/data
    networks:
      - photo_network

networks:
  photo_network:
    driver: bridge

volumes:
  minio_data:
